### PR TITLE
The IOS app repo lacks the license file

### PR DESCRIPTION
**Pull request by haslinger**

### CODE REVIEW

**Comment by hola-soy-milk** [comment]
Good catch, thank you very much @haslinger!

**Comment by haslinger** [comment]
That's weird, the file doesn't show up, although you merged...

**Comment by haslinger** [comment]
Got it, you just closed it without merging. I merged it now.

**Comment by hola-soy-milk** [comment]
Oh my god, I'm sorry @haslinger. I pressed the wrong button :(

**Pull request merged**
